### ISSUE TITLE
timeouted tasks

### ISSUE THREAD

**Issue by Sparkycz** [fabregas/aiokafka_rpc#3]
Hey there,

What happens if the server-side process takes longer than 10 sec. (timeout) ? Will the response message remain in Kafka?

thanks for the answer.
VK

**Comment by fabregas** [comment]
Hello, Vladimir,
Now aiokafka_rpc is not support timeout for rpc method call.
10 sec timeout is a timeout for closing client/server. So if you closing
client and some in-progress rpc call takes longer than 10 sec, response
will be produced to Kafka out-topic but 'nobody' can handle it, it will be
just skipped.

Thanks

2018-01-07 22:11 GMT+02:00 Vladimir Kaspar <notifications@github.com>:
